version: '3'

services:
  service:
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
      
  website:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - 3000:3000


  